# From https://github.com/marketplace/actions/pypi-publish
# This is a basic workflow to help you get started with Actions
on:
  release:
    types: [published]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install wheel
      - name: Check the dir
        run: |
              ls 
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Publish a Python distribution to PyPI
        # Might want to add but does not work on workflow_dispatch if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user:  ${{ secrets.token }}
          password: ${{ secrets.pypi_password }}
